### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by rivimont** [cryptoaustralia/dingoes#1]
In README.md to run it mentions running dyngoes.py but the actual file is called dingoes.py. 

Either way when running it get the following error:

laptop:dingoes userName$ python dingoes.py
Traceback (most recent call last):
  File "dingoes.py", line 15, in <module>
    from dingoes.report import Report
  File "/Users/userName/git/dingoes/dingoes/report.py", line 109
    print(bar, end='\r')
                  ^
SyntaxError: invalid syntax

**Comment by gszathmari** [comment]
Hi @rivimont, thank you for the bug report, I am fixing the typo now
